dist: xenial
language: python
cache: pip

python:
    - 3.7

install :
#    - pip install Flask
#    - pip install ipaddress
    - pip install requests
#    - pip install pymsteams
    - pip install gitpython

    - pip install pre-commit
    - pip install flake8
    - pip install black
    - pip install codecov
    - pip install coverage

before_script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

script:
    - pre-commit run --all-files
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    # black: do not format files, throw colorful diff
    - black --check .
    - coverage run app/test_clone.py

notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down

after_success:
    #sudo: required
    - bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
